#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'PRIME_NO' function below.
#
# The function accepts INTEGER n as parameter.
#

def PRIME_NO(n):
    if(n<=1):
        print("NOT PRIME NUMBER")
    else:
        for i in range(2,n//2+1):
            if(n%i==0):
                print("NOT PRIME NUMBER")
                break
        else:
                print("PRIME NUMBER")
        

def PRIME_NOS_UPTO_N(n):
    if(n<=1):
        print("INVALID INPUT")
    else:
        for j in range(2,n+1):
            for i in range(2,j//2+1):
                if(j%i==0):
                    break
            else:
                    print(j,end=" ")
            
           
               



if __name__ == '__main__':
    n = int(input().strip())

    PRIME_NO(n)

    PRIME_NOS_UPTO_N(n)
